### ISSUE TITLE
Paquete repository

### ISSUE THREAD

**Issue by Martajua** [Martajua/repo-TP2-Grupo12#92]
Crear el paquete repository y cree las interfaces necesarias. Identifique los métodos para realizar las consultas de los datos.

**Comment by JorgeArielS93** [comment]
Me encuentro realizando esta tarea

**Comment by JorgeArielS93** [comment]
Se commitio un avance de la tarea en el Proyecto.
Faltan agregar los metodos: 
  * Mostrar los productos según una categoría.
  * Mostrar los servicios según el día seleccionado.
  * Mostrar las sucursales que están entre una fechaInicio y fechaFin.
Si la Profesora no lo explica en la clase de consuta del 15/06/23 como hacerlos yo buscare la forma.

**Comment by JorgeArielS93** [comment]
No eh podido lanzar el proyecto por que me manda un mensaje de conflicto, hice lo que me decia el mensaje pero no lo pude solucionar.


![Image](https://github.com/Martajua/repo-TP2-Grupo12/assets/70386725/15f250be-b563-4c50-87e5-bffffdeddc75)

**Comment by JorgeArielS93** [comment]
Se corrigieron los erroes, la aplicacion se conecta correctamente a la base de datos MySQL


![Image](https://github.com/Martajua/repo-TP2-Grupo12/assets/70386725/cdb395dc-d93c-4b74-916b-3d0ef460f364)
